[files]
extend-exclude = [
  'CHANGELOG.md',
  'smarthr-ui-props.json',
  'packages/smarthr-ui/src/intl/locales/pt_br.ts',
]

[default.extend-words]
# togglable is correct spelling (toggleable is just an alternative form)
togglable = "togglable"
