name: publish release (charts)

on:
  issues:
    types:
      - labeled

jobs:
  publish_release:
    if: github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'charts release candidate') && github.event.label.name == 'approve charts release'
    runs-on: ubuntu-latest
    env:
      CHANGELOG_PATH: /tmp/CHANGELOG.md
      IS_PRERELEASE: ${{ contains(github.event.issue.labels.*.name, 'charts prerelease') }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: release-candidate-charts
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
      - name: git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: pnpm install
        run: |
          npm install -g corepack@latest
          corepack enable
          corepack prepare
          pnpm install --filter @smarthr/smarthr-ui-charts
      - run: pnpm --filter @smarthr/smarthr-ui-charts release
        if: ${{ env.IS_PRERELEASE == 'false' }}
      - run: pnpm --filter @smarthr/smarthr-ui-charts release --prerelease
        if: ${{ env.IS_PRERELEASE == 'true' }}
      - run: pnpm publish --filter @smarthr/smarthr-ui-charts --no-git-checks
        if: ${{ env.IS_PRERELEASE == 'false' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.KUFU_NPM_RELEASE_TOKEN }}
      - run: pnpm publish --filter @smarthr/smarthr-ui-charts --tag prerelease --no-git-checks
        if: ${{ env.IS_PRERELEASE == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.KUFU_NPM_RELEASE_TOKEN }}
      - run: echo NEW_TAG=$(git describe) >> $GITHUB_ENV
      - name: extract version from tag
        run: echo VERSION=$(echo $NEW_TAG | sed 's/@smarthr\/smarthr-ui-charts@//') >> $GITHUB_ENV
      - run: git push origin $NEW_TAG
      - run: npx node --loader ts-node/esm ./scripts/getLatestChangelog.ts > ${{ env.CHANGELOG_PATH }}
        working-directory: ./packages/charts
      - name: create release on GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: ${{ env.NEW_TAG }}
          body_path: ${{ env.CHANGELOG_PATH }}
          commitish: master
          prerelease: ${{ env.IS_PRERELEASE }}
      - name: close issue
        uses: peter-evans/close-issue@v3
      - name: delete branch
        run: git push origin :release-candidate-charts
      - name: cherry-pick release commit
        run: |
          git checkout master
          git cherry-pick $NEW_TAG
      - name: create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore(charts): ${{ env.NEW_TAG }}'
          branch: 'merge-release-charts-${{ env.VERSION }}'
          labels: charts release candidate
      - name: Send message to Slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            text: "<!subteam^S01RJL6PHJ8> @smarthr/smarthr-ui-charts の npm publish が完了しました。Release Pull Request を手動でマージしたらリリース完了です。"
