name: close release candidate (charts)

on:
  issues:
    types:
      - closed

jobs:
  close_release_candidate:
    if: contains(github.event.issue.labels.*.name, 'charts release candidate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: delete branch
        run: git push origin :release-candidate-charts
