name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - name: git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: prepare release
        run: |
          base_tag=v$(npx -c 'echo "$npm_package_version"')
          git checkout $base_tag
          git merge --no-edit ${{ github.ref }}
          yarn install
      - name: run release
        run: |
          yarn release
          echo "new_tag=$(git describe)" >> $GITHUB_ENV
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: push release
        run: |
          git push origin $new_tag
          git checkout master
          git cherry-pick $new_tag
      - name: craete PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'chore(release): ${{ env.new_tag }}'
