name: Typo Checker
on: [pull_request]

jobs:
  run:
    name: Typo Checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use custom config file
      uses: crate-ci/typos@master
      with:
        config: ./.typos.toml
